const COMMANDS = [
  ["me",           "profile overview"],
  ["artists",      "top artists"],
  ["tracks",       "top tracks"],
  ["albums",       "top albums"],
  ["recent",       "recent scrobbles"],
  ["now",          "now playing"],
  ["streak",       "daily scrobble streak"],
  ["loved",        "loved tracks"],
  ["compare",      "compare two periods"],
  ["peak",         "peak listening days"],
  ["heatmap",      "scrobble heatmap"],
  ["milestones",   "scrobble milestones"],
  ["hour",         "listening by hour"],
  ["day",          "listening by weekday"],
  ["wrapped",      "annual wrapped"],
  ["artist",       "artist deep dive"],
  ["similar",      "similar artists"],
  ["tag",          "top artists for a tag"],
  ["underground",  "artists with few listeners"],
  ["forgotten",    "artists you stopped listening to"],
  ["new",          "artists discovered this month"],
  ["obsession",    "current listening obsession"],
  ["compare-user", "compare two profiles"],
  ["compat",       "musical compatibility score"],
  ["friends",      "what friends are listening to"],
  ["friends-top",  "friends top artists"],
  ["auth",         "authenticate for write operations"],
  ["love",         "love a track"],
  ["unlove",       "unlove a track"],
  ["ban",          "ban a track"],
  ["love-now",     "love the currently playing track"],
  ["export",       "export scrobbles"],
  ["backup",       "full profile backup"],
  ["stats-raw",    "raw profile stats as JSON"],
  ["cache",        "manage local cache"],
  ["setup",        "interactive setup wizard"],
  ["config",       "set API key and username"],
];

const PERIODS = ["7day", "1month", "3month", "6month", "12month", "overall"];

export function cmdCompletions(shell) {
  switch (shell) {
    case "fish":  return fishCompletions();
    case "zsh":   return zshCompletions();
    case "bash":  return bashCompletions();
    default:
      console.error(`\x1b[31m✗ unknown shell: ${shell}. use: fish, zsh, bash\x1b[0m`);
      process.exit(1);
  }
}

function fishCompletions() {
  const lines = [
    "# scrobblr fish completions",
    "# generated by: scrobblr completions fish",
    "",
    "# disable file completions for scrobblr",
    "complete -c scrobblr -f",
    "",
    "# commands",
  ];

  for (const [cmd, desc] of COMMANDS) {
    lines.push(`complete -c scrobblr -n '__fish_use_subcommand' -a '${cmd}' -d '${desc}'`);
  }

  lines.push("");
  lines.push("# period options");
  const periodCmds = ["artists", "tracks", "albums", "compare", "compare-user", "compat", "friends-top", "wrapped"];
  for (const cmd of periodCmds) {
    for (const p of PERIODS) {
      lines.push(`complete -c scrobblr -n '__fish_seen_subcommand_from ${cmd}' -l period -a '${p}'`);
    }
  }

  lines.push("");
  lines.push("# common flags");
  lines.push("complete -c scrobblr -l json -d 'raw JSON output'");
  lines.push("complete -c scrobblr -l limit -d 'number of results'");
  lines.push("complete -c scrobblr -l no-color -d 'disable colors'");
  lines.push("complete -c scrobblr -n '__fish_seen_subcommand_from recent' -l live -d 'auto-refresh every 30s'");
  lines.push("complete -c scrobblr -n '__fish_seen_subcommand_from now' -l info -d 'show track details'");

  console.log(lines.join("\n"));
}

function zshCompletions() {
  const cmdList = COMMANDS.map(([cmd, desc]) => `    '${cmd}:${desc}'`).join("\n");
  const periodList = PERIODS.join(" ");

  console.log(`#compdef scrobblr
# scrobblr zsh completions
# generated by: scrobblr completions zsh

_scrobblr() {
  local state

  _arguments \\
    '1: :->command' \\
    '*: :->args'

  case $state in
    command)
      local commands=(
${cmdList}
      )
      _describe 'command' commands
      ;;
    args)
      case $words[2] in
        artists|tracks|albums|compare|compare-user|compat|friends-top|wrapped)
          _arguments '-p[period]:period:(${periodList})'
          ;;
      esac
      ;;
  esac
}

_scrobblr`);
}

function bashCompletions() {
  const cmdList = COMMANDS.map(([cmd]) => cmd).join(" ");
  const periodList = PERIODS.join(" ");

  console.log(`# scrobblr bash completions
# generated by: scrobblr completions bash
# add to ~/.bashrc: source <(scrobblr completions bash)

_scrobblr_completions() {
  local cur prev
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"

  if [ $COMP_CWORD -eq 1 ]; then
    COMPREPLY=($(compgen -W "${cmdList}" -- "$cur"))
    return
  fi

  case "$prev" in
    -p|--period)
      COMPREPLY=($(compgen -W "${periodList}" -- "$cur"))
      return
      ;;
  esac
}

complete -F _scrobblr_completions scrobblr`);
}
